[2022-03-15 20:18:24,083] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.get_recipes scheduled__2022-03-15T20:16:55.141162+00:00 [queued]>
[2022-03-15 20:18:24,091] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.get_recipes scheduled__2022-03-15T20:16:55.141162+00:00 [queued]>
[2022-03-15 20:18:24,091] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 20:18:24,091] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-15 20:18:24,091] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 20:18:24,099] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): get_recipes> on 2022-03-15 20:16:55.141162+00:00
[2022-03-15 20:18:24,103] {standard_task_runner.py:52} INFO - Started process 37249 to run task
[2022-03-15 20:18:24,110] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'get_recipes', 'scheduled__2022-03-15T20:16:55.141162+00:00', '--job-id', '380', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpz7h02x1b', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpy4zhz1ol']
[2022-03-15 20:18:24,113] {standard_task_runner.py:77} INFO - Job 380: Subtask get_recipes
[2022-03-15 20:18:24,163] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.get_recipes scheduled__2022-03-15T20:16:55.141162+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-15 20:18:24,201] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=get_recipes
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T20:16:55.141162+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-15T20:16:55.141162+00:00
[2022-03-15 20:18:24,215] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:24,216] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:24,638] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:24,639] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:28,111] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:28,112] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:28,851] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:28,852] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:29,711] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:29,712] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:30,430] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:30,430] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:31,228] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:31,229] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:31,932] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:31,933] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:32,900] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:32,901] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:33,613] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:33,614] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:34,483] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:34,485] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:35,296] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:35,309] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:36,066] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:36,068] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:36,864] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:36,865] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:37,835] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:37,836] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:38,644] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:38,646] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:39,319] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:39,321] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:40,120] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:40,121] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:40,898] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:40,899] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:41,977] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:41,978] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:42,955] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:42,956] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:43,686] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:43,687] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:44,456] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:44,457] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:45,099] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:45,100] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:46,069] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:46,071] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:46,886] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:46,887] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:47,576] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:47,577] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:48,312] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:48,314] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:49,113] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:49,115] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:49,947] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:49,948] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:50,644] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:50,646] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:51,393] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:51,394] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:52,128] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:52,129] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:52,850] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:52,851] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:53,828] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:53,830] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:54,532] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:54,533] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:55,562] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:55,563] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:56,322] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:56,323] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:57,083] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:57,084] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:58,001] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:58,003] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:58,664] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 20:18:58,689] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 20:18:59,808] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 145, in get_recipes
    recipedata = bytes(json.dumps(dfuser.to_json(orient="records")).encode('UTF-8'))
NameError: name 'dfuser' is not defined
[2022-03-15 20:18:59,825] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=simple_dag, task_id=get_recipes, execution_date=20220315T201655, start_date=20220316T011824, end_date=20220316T011859
[2022-03-15 20:18:59,834] {standard_task_runner.py:89} ERROR - Failed to execute job 380 for task get_recipes
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 145, in get_recipes
    recipedata = bytes(json.dumps(dfuser.to_json(orient="records")).encode('UTF-8'))
NameError: name 'dfuser' is not defined
[2022-03-15 20:18:59,867] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-15 20:18:59,897] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
