[2022-03-14 09:57:17,459] {processor.py:163} INFO - Started process (PID=75806) to work on /Users/HomeFolder/airflow/dags/s3_dag_test.py
[2022-03-14 09:57:17,459] {processor.py:642} INFO - Processing file /Users/HomeFolder/airflow/dags/s3_dag_test.py for tasks to queue
[2022-03-14 09:57:17,460] {logging_mixin.py:109} INFO - [2022-03-14 09:57:17,460] {dagbag.py:500} INFO - Filling up the DagBag from /Users/HomeFolder/airflow/dags/s3_dag_test.py
[2022-03-14 09:57:17,465] {logging_mixin.py:109} INFO - [2022-03-14 09:57:17,463] {dagbag.py:334} ERROR - Failed to import: /Users/HomeFolder/airflow/dags/s3_dag_test.py
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/HomeFolder/airflow/dags/s3_dag_test.py", line 2, in <module>
    from airflow.operators import SimpleHttpOperator, HttpSensor,   BashOperator, EmailOperator, S3KeySensor
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.operators' (/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/__init__.py)
[2022-03-14 09:57:17,488] {processor.py:656} WARNING - No viable dags retrieved from /Users/HomeFolder/airflow/dags/s3_dag_test.py
[2022-03-14 09:57:17,494] {processor.py:171} INFO - Processing /Users/HomeFolder/airflow/dags/s3_dag_test.py took 0.035 seconds
[2022-03-14 09:58:10,207] {processor.py:163} INFO - Started process (PID=75845) to work on /Users/HomeFolder/airflow/dags/s3_dag_test.py
[2022-03-14 09:58:10,208] {processor.py:642} INFO - Processing file /Users/HomeFolder/airflow/dags/s3_dag_test.py for tasks to queue
[2022-03-14 09:58:10,208] {logging_mixin.py:109} INFO - [2022-03-14 09:58:10,208] {dagbag.py:500} INFO - Filling up the DagBag from /Users/HomeFolder/airflow/dags/s3_dag_test.py
[2022-03-14 09:58:10,212] {logging_mixin.py:109} INFO - [2022-03-14 09:58:10,211] {dagbag.py:334} ERROR - Failed to import: /Users/HomeFolder/airflow/dags/s3_dag_test.py
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/HomeFolder/airflow/dags/s3_dag_test.py", line 2, in <module>
    from airflow.operators import SimpleHttpOperator, HttpSensor,   BashOperator, EmailOperator, S3KeySensor
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.operators' (/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/__init__.py)
[2022-03-14 09:58:10,234] {processor.py:656} WARNING - No viable dags retrieved from /Users/HomeFolder/airflow/dags/s3_dag_test.py
[2022-03-14 09:58:10,246] {processor.py:171} INFO - Processing /Users/HomeFolder/airflow/dags/s3_dag_test.py took 0.040 seconds
[2022-03-14 09:58:53,524] {processor.py:163} INFO - Started process (PID=75936) to work on /Users/HomeFolder/airflow/dags/s3_dag_test.py
[2022-03-14 09:58:53,524] {processor.py:642} INFO - Processing file /Users/HomeFolder/airflow/dags/s3_dag_test.py for tasks to queue
[2022-03-14 09:58:53,525] {logging_mixin.py:109} INFO - [2022-03-14 09:58:53,525] {dagbag.py:500} INFO - Filling up the DagBag from /Users/HomeFolder/airflow/dags/s3_dag_test.py
[2022-03-14 09:58:53,528] {logging_mixin.py:109} INFO - [2022-03-14 09:58:53,527] {dagbag.py:334} ERROR - Failed to import: /Users/HomeFolder/airflow/dags/s3_dag_test.py
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/HomeFolder/airflow/dags/s3_dag_test.py", line 2, in <module>
    from airflow.operators import SimpleHttpOperator, HttpSensor,   BashOperator, EmailOperator, S3KeySensor
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.operators' (/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/__init__.py)
[2022-03-14 09:58:53,552] {processor.py:656} WARNING - No viable dags retrieved from /Users/HomeFolder/airflow/dags/s3_dag_test.py
[2022-03-14 09:58:53,561] {processor.py:171} INFO - Processing /Users/HomeFolder/airflow/dags/s3_dag_test.py took 0.038 seconds
[2022-03-14 10:00:43,435] {processor.py:163} INFO - Started process (PID=76003) to work on /Users/HomeFolder/airflow/dags/s3_dag_test.py
[2022-03-14 10:00:43,435] {processor.py:642} INFO - Processing file /Users/HomeFolder/airflow/dags/s3_dag_test.py for tasks to queue
[2022-03-14 10:00:43,436] {logging_mixin.py:109} INFO - [2022-03-14 10:00:43,436] {dagbag.py:500} INFO - Filling up the DagBag from /Users/HomeFolder/airflow/dags/s3_dag_test.py
[2022-03-14 10:00:43,439] {logging_mixin.py:109} INFO - [2022-03-14 10:00:43,438] {dagbag.py:334} ERROR - Failed to import: /Users/HomeFolder/airflow/dags/s3_dag_test.py
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/HomeFolder/airflow/dags/s3_dag_test.py", line 2, in <module>
    from airflow.operators import SimpleHttpOperator, HttpSensor,   BashOperator, EmailOperator, S3KeySensor
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.operators' (/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/__init__.py)
[2022-03-14 10:00:43,465] {processor.py:656} WARNING - No viable dags retrieved from /Users/HomeFolder/airflow/dags/s3_dag_test.py
[2022-03-14 10:00:43,476] {processor.py:171} INFO - Processing /Users/HomeFolder/airflow/dags/s3_dag_test.py took 0.042 seconds
